name: Push

on:
  workflow_dispatch:
    inputs:
      package:
        description: 'Package'
        required: true
        type: choice
        options:
          - fluentd
          - ipsec
          - keydb
          - nginx-openrestry
          - openvpn
          - pgbouncer
          - postgresql
          - tabix

jobs:
  build-push:
    name: "Build image and push"
    runs-on: ubuntu-22.04
    permissions:
      contents: read
      packages: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        run: make init
      - name: Github registry login
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build
        timeout-minutes: 15
        run: make package-${{ inputs.package }}
        env:
          PUSH: "true"
